FROM python:3.8-slim

RUN mkdir /app && mkdir /app/static /app/templates /app/modelos

WORKDIR /app

COPY static/ /app/static/
COPY templates/ /app/templates/
COPY modelos/ /app/modelos/

COPY docker/requirements-appweb.txt /app/requirements.txt 
COPY 81-aplicacao-servico-rest.py /app/app.py

#COPY . /app
#RUN mv /app/81-aplicacao-servico-rest.py /app/app.py

RUN pip install \
  --trusted-host pypi.org --trusted-host files.pythonhosted.org \
  -r requirements.txt

EXPOSE 5000

ENV PYTHONPATH /app
ENV PYTHONIOENCODING utf-8

CMD python app.py
