# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genero_nome.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='genero_nome.proto',
  package='generonome',
  syntax='proto3',
  serialized_options=b'\n0com.github.hjort.analisepessoasbrasil.generonomeB\017GeneroNomeProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11genero_nome.proto\x12\ngeneronome\"!\n\x11GeneroNomeRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"!\n\x0fGeneroNomeReply\x12\x0e\n\x06genero\x18\x01 \x01(\x05\x32\x66\n\x12GeneroNomePreditor\x12P\n\x10PreverGeneroNome\x12\x1d.generonome.GeneroNomeRequest\x1a\x1b.generonome.GeneroNomeReply\"\x00\x42K\n0com.github.hjort.analisepessoasbrasil.generonomeB\x0fGeneroNomeProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_GENERONOMEREQUEST = _descriptor.Descriptor(
  name='GeneroNomeRequest',
  full_name='generonome.GeneroNomeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='generonome.GeneroNomeRequest.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=66,
)


_GENERONOMEREPLY = _descriptor.Descriptor(
  name='GeneroNomeReply',
  full_name='generonome.GeneroNomeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='genero', full_name='generonome.GeneroNomeReply.genero', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['GeneroNomeRequest'] = _GENERONOMEREQUEST
DESCRIPTOR.message_types_by_name['GeneroNomeReply'] = _GENERONOMEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneroNomeRequest = _reflection.GeneratedProtocolMessageType('GeneroNomeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERONOMEREQUEST,
  '__module__' : 'genero_nome_pb2'
  # @@protoc_insertion_point(class_scope:generonome.GeneroNomeRequest)
  })
_sym_db.RegisterMessage(GeneroNomeRequest)

GeneroNomeReply = _reflection.GeneratedProtocolMessageType('GeneroNomeReply', (_message.Message,), {
  'DESCRIPTOR' : _GENERONOMEREPLY,
  '__module__' : 'genero_nome_pb2'
  # @@protoc_insertion_point(class_scope:generonome.GeneroNomeReply)
  })
_sym_db.RegisterMessage(GeneroNomeReply)


DESCRIPTOR._options = None

_GENERONOMEPREDITOR = _descriptor.ServiceDescriptor(
  name='GeneroNomePreditor',
  full_name='generonome.GeneroNomePreditor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=103,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='PreverGeneroNome',
    full_name='generonome.GeneroNomePreditor.PreverGeneroNome',
    index=0,
    containing_service=None,
    input_type=_GENERONOMEREQUEST,
    output_type=_GENERONOMEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENERONOMEPREDITOR)

DESCRIPTOR.services_by_name['GeneroNomePreditor'] = _GENERONOMEPREDITOR

# @@protoc_insertion_point(module_scope)
