# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc import genero_nome_pb2 as grpc_dot_genero__nome__pb2


class GeneroNomePreditorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PreverGeneroNome = channel.unary_unary(
                '/generonome.GeneroNomePreditor/PreverGeneroNome',
                request_serializer=grpc_dot_genero__nome__pb2.GeneroNomeRequest.SerializeToString,
                response_deserializer=grpc_dot_genero__nome__pb2.GeneroNomeReply.FromString,
                )


class GeneroNomePreditorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PreverGeneroNome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneroNomePreditorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PreverGeneroNome': grpc.unary_unary_rpc_method_handler(
                    servicer.PreverGeneroNome,
                    request_deserializer=grpc_dot_genero__nome__pb2.GeneroNomeRequest.FromString,
                    response_serializer=grpc_dot_genero__nome__pb2.GeneroNomeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generonome.GeneroNomePreditor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GeneroNomePreditor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PreverGeneroNome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/generonome.GeneroNomePreditor/PreverGeneroNome',
            grpc_dot_genero__nome__pb2.GeneroNomeRequest.SerializeToString,
            grpc_dot_genero__nome__pb2.GeneroNomeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
